server:
  port: 8081

spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:mysql://mysql-doctor:3306/patient_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: redis-server
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka